#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
    touch $SERVICE_CONFIG
  fi
  config::load_file $SERVICE_CONFIG

  if [ ! -f $SERVICE_INGRESS_CONFIG_DIR_ROUTER ]; then
    log::error "[ingress] cannot found config in $SERVICE_INGRESS_CONFIG_DIR_ROUTER"
    exit 1
  fi

  if [ -z "$SERVICE_INGRESS_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_INGRESS_DOMAIN:" value
    config::set SERVICE_INGRESS_DOMAIN $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_INGRESS_IS_LOCAL" ]; then
    local choices=(
      "No"
      "Yes"
    )
    inquirer::select "是否 SERVICE_INGRESS_IS_LOCAL？yes or No" choices value
    if [ "$value" = "Yes" ]; then
      value=true
    else
      value=false
    fi

    config::set SERVICE_INGRESS_IS_LOCAL $value $SERVICE_CONFIG
    #
    SERVICE_INGRESS_IS_LOCAL=$value
  fi

  if [ "$SERVICE_INGRESS_IS_LOCAL" = "false" ]; then
    local SERVICE_INGRESS_DOMAIN_SSL=$SERVICE_INGRESS_SSL/$SERVICE_INGRESS_DOMAIN
    if [ ! -d $SERVICE_INGRESS_DOMAIN_SSL ]; then
      log::error "[ingress] cannot found ssl directory for $SERVICE_INGRESS_DOMAIN"
      exit 1
    fi
  fi

  # load again
  config::load_file $SERVICE_CONFIG

  # @TODO
  export SERVICE_INGRESS_DOMAIN=$SERVICE_INGRESS_DOMAIN
  export SERVICE_INGRESS_IS_LOCAL=$SERVICE_INGRESS_IS_LOCAL
  export SERVICE_INGRESS_HTTP_PORT=$SERVICE_INGRESS_HTTP_PORT
  export SERVICE_INGRESS_HTTPS_PORT=$SERVICE_INGRESS_HTTPS_PORT

  if [ "$SERVICE_INGRESS_IS_LOCAL" = "true" ]; then
    export SERVICE_INGRESS_FORCE_HTTPS=false
  fi

  if [ "$SERVICE_INGRESS_HTTPS" = "true" ]; then
    if [ -z "$SERVICE_INGRESS_HTTPS_PORT" ]; then
      inquirer::text "请输入 SERVICE_INGRESS_HTTPS_PORT:" value
      config::set SERVICE_INGRESS_HTTPS_PORT $value $SERVICE_CONFIG
    fi

    config::load_file $SERVICE_CONFIG
  else

  if [ -z "$SERVICE_INGRESS_HTTP_PORT" ]; then
      inquirer::text "请输入 SERVICE_INGRESS_HTTP_PORT:" value
      config::set SERVICE_INGRESS_HTTP_PORT $value $SERVICE_CONFIG
    fi

    config::load_file $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_INGRESS_HTTPS_PORT" ]; then
      inquirer::text "请输入 SERVICE_INGRESS_HTTPS_PORT:" value
      config::set SERVICE_INGRESS_HTTPS_PORT $value $SERVICE_CONFIG
    fi

    config::load_file $SERVICE_CONFIG
  fi
}

check $@
