version: '3.7'

services:
  ingress:
    restart: always
    image: whatwewant/open-ingress:${SERVICE_INGRESS_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_INGRESS_HTTP_PORT}:80
      - 0.0.0.0:${SERVICE_INGRESS_HTTPS_PORT}:443
    environment:
      # MODE: debug
      FORCE_HTTPS: "${SERVICE_INGRESS_FORCE_HTTPS}"
      TZ: Aisa/Shanghai
    volumes:
      - ${SERVICE_INGRESS_CONFIG_DIR}:/app/conf/config
      - ${SERVICE_INGRESS_CONFIG_DIR}/ssl:/config/ssl
      - ${SERVICE_LOGS}/waf:/var/log/waf

networks:
  default:
    external: true
    name: ${SERVICE_NETWORK:-compose-ingress}
