version: '3.7'

services:
  ingress:
    restart: always
    image: whatwewant/open-ingress:${SERVICE_INGRESS_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_INGRESS_HTTP_PORT}:80
      - 0.0.0.0:${SERVICE_INGRESS_HTTPS_PORT}:443
    environment:
      DOMAIN: ${SERVICE_INGRESS_DOMAIN}
      # MODE: debug
      HTTPS: "${SERVICE_INGRESS_HTTPS}"
    volumes:
      - ${SERVICE_CONFIGS}:/app/conf/config
      - ${SERVICE_CONFIGS}/ssl:/config/ssl
      - ${SERVICE_LOGS}/waf:/var/log/waf

networks:
  default:
    external: true
    name: ${SERVICE_NETWORK:-compose-ingress}
